---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: the-listener
spec:
  triggers:
  - binding:
      name: theTriggerBinding
    template:
      name: theTemplateTrigger
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: theTriggerBinding
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: theTemplateTrigger
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: pipelinerun-$(uid)
    spec:
      pipelineRef:
        name: hello-goodbye
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: hello-goodbye
spec:
  tasks:
  - name: hello
    taskRef:
      name: hello
  - name: afternoon
    runAfter: [hello]
    taskRef: 
      name: afternoon
  - name: goodbye
    runAfter: [hello, afternoon]
    taskRef:
      name: goodbye
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: goodbye
spec:
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Goodbye World!"
 ---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: afternoon
spec:
  steps:
    - name: mid-day
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Good Afternoon!"
 ---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: hello
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World!"
