---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: the-listener
spec:
  triggers:
  - binding:
      name: theTriggerBinding
    template:
      name: theTemplateTrigger
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: theTriggerBinding
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: theTemplateTrigger
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: pipelinerun-$(uid)
    spec:
      pipelineRef:
        name: hello-goodbye
